import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiOutlineGithub, AiTwotoneMail } from "react-icons/ai";
import Image from "next/legacy/image";
import webdev from "../public/web-dev-robertaf.png";
import pambagif from "../public/Pamba.gif";
import airbnbclone from "../public/Airbnb-Clone.gif"
import { useState } from "react";


export default function Home() {
  const [currentYear, setCurrentYear] = useState(new Date().getFullYear());

  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Roberta Freitas Portfolio</title>
        <meta name="description" content="Generated by Roberta Freitas" />
        <link rel="icon" href="/favicon-portfolio.ico" />
      </Head>
      <main className=" bg-white px-10 md:px-20 lg:px4 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className=" py-10 mb-12 flex justify-between dark:text-white">
          <h1 className=" text-xl font-burtons">developedbyroberta</h1>
            <ul className=" flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl"/>
              </li>
              <li>
                <a className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="https://www.canva.com/design/DAFvRumdVu0/6c_zMm19E1jng7eHlDt1aQ/edit?utm_content=DAFvRumdVu0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton">Resume</a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className=" text-2xl py-2 font-medium dark:text-teal-400">
              Hi, I am Roberta Freitas
            </h2>
            <h3 className=" text-5xl py-2 dark:text-white">I am a <span className="text-teal-500"> Web Developer </span></h3>
            <p className=" text-md leading-8 text-gray-800 dark:text-gray-200">Welcome to my Portfolio.</p>
          </div>

          <div className=" text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a href="https://www.linkedin.com/in/roberta-efreitas/" target="_blank" rel="noopener noreferrer">
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/Roberta-Freitas" target="_blank" rel="noopener noreferrer">
              <AiOutlineGithub/>
            </a>
            <a href="mailto:robertaefreitas@gmail.com">
              <AiTwotoneMail />
            </a>
          </div>

          <div className="mt-20 flex justify-center">
            <div className="relative bg-gradient-to-b from-teal-500 rounded-full h-80 w-80 flex justify-center items-center overflow-hidden">
              <div >
                <Image
                  src={webdev}
                  alt="Roberta Web Developer"
                 />
            </div>
          </div>
        </div>
      </section>
      {/* Projects page starts here */}
      <section>
        <div>
          <h2 className="mt-20 text-3xl py-1 dark:text-white">Projects</h2>
        </div>
      {/* Card section starts here */}
      <div>
      {/* First Card */}
        <div className=" text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-100">
          <Image src={pambagif} alt="Pamba Project" />
          <h3 className=" text-lg font-medium pt-8 pb-2">Pamba - Your home Away from Home</h3>
          <p className="py-2">
            As the final project of the Web Development Bootcamp,
            my 3 team mates and I built Pamba, a web-app that helps future
            Le Wagon students to find accommodation based on previous students reviews.
          </p>
          <h4 className="py-4 text-teal-600">Main features:</h4>
            <ul>
              <li className="text-gray-800 py-1">API from ns.nl to search for commute options</li>
              <li className="text-gray-800 py-1">Geocoder</li>
              <li className="text-gray-800 py-1">Mapbox</li>
            </ul>
        </div>

      {/* Second Card */}
        <div className=" text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-100">
          <Image src={airbnbclone} alt="Airbnb Clone Project" />
          <h3 className=" text-lg font-medium pt-8 pb-2">Airbnb Clone</h3>
          <p className="py-2">
            {/* I have to write the description */}
          </p>
          <h4 className="py-4 text-teal-600">Main features:</h4>
            <ul>
              <li className="text-gray-800 py-1">Feature 1</li>
              <li className="text-gray-800 py-1">Feature 2</li>
              <li className="text-gray-800 py-1">Feature 3</li>
            </ul>
        </div>

        {/* Third Card */}
        <div className=" text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-100">
          <Image src={airbnbclone} alt="Airbnb Clone Project" />
          <h3 className=" text-lg font-medium pt-8 pb-2">Airbnb Clone</h3>
          <p className="py-2">
          {/* I have to write the description */}
          </p>
          <h4 className="py-4 text-teal-600">Main features:</h4>
            <ul>
              <li className="text-gray-800 py-1">API from ns.nl to search for commute options</li>
              <li className="text-gray-800 py-1">Geocoder</li>
              <li className="text-gray-800 py-1">Mapbox</li>
            </ul>
        </div>

         {/* Forth Card */}
        <div className=" text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-100">
          <Image src={airbnbclone} alt="Airbnb Clone Project" />
          <h3 className=" text-lg font-medium pt-8 pb-2">Airbnb Clone</h3>
          <p className="py-2">
          {/* I have to write the description */}
          </p>
          <h4 className="py-4 text-teal-600">Main features:</h4>
            <ul>
              <li className="text-gray-800 py-1">API from ns.nl to search for commute options</li>
              <li className="text-gray-800 py-1">Geocoder</li>
              <li className="text-gray-800 py-1">Mapbox</li>
            </ul>
         </div>

         {/* Fifth Card */}
         <div className=" text-center shadow-lg p-10 rounded-xl my-10  dark:bg-gray-100">
          <Image src={airbnbclone} alt="Airbnb Clone Project" />
          <h3 className=" text-lg font-medium pt-8 pb-2">Airbnb Clone</h3>
          <p className="py-2">
          {/* I have to write the description */}
          </p>
          <h4 className="py-4 text-teal-600">Main features:</h4>
            <ul>
              <li className="text-gray-800 py-1">API from ns.nl to search for commute options</li>
              <li className="text-gray-800 py-1">Geocoder</li>
              <li className="text-gray-800 py-1">Mapbox</li>
            </ul>
          </div>
      </div>
      </section>

      <section>
      {/* Skills part starts here */}
      <div>
        <h3 className=" text-3xl py-1 mt-10 dark:text-white">Skills</h3>
        {/* Make cards with skills */}
      </div>
      </section>

      <section>
      {/* About Me starts here */}
      <div>
        <h3 className=" text-3xl py-1 mt-10 dark:text-white">About Me</h3>
        <p className=" text-md py-2 leading-8 text-gray-800 dark:text-gray-200">I wasnt always a web developer. Previously I worked as Guest Relations Manager of a boutique hotel, however in my free time, I pursued my passion for web development and built a few Shopify stores. I also managed Facebook ad campaigns for these stores.</p>
        <p className=" text-md py-2 leading-8 text-gray-800 dark:text-gray-200">In December 2022, I quit my job and decided to dive deeper in the world of web development.</p>
        <p className=" text-md py-2 leading-8 text-gray-800 dark:text-gray-200">In January 2023, I joined the very intensive <span className="text-teal-500">  360-hours Le Wagon Bootcamp</span> in Amsterdam. Right after that, in April, I immediately embarked on another exciting learning journey by enrolling in the App Brewery online bootcamp. This program teaches React, Nodejs, EJS, MongoDB, Blockchain, Motoko and more.</p>
        <p className=" text-md py-2 leading-8 text-gray-800 dark:text-gray-200">I have had the opportunity of living in Australia, the United States, Brazil, Portugal and now in the Netherlands, and have traveled to all five continents during the time I worked for the Dutch cruise line Holland America Line. Through these experiences, I have developed a deep appreciation for cultural diversity and a global perspective.</p>
        <p className=" text-md py-2 leading-8 text-gray-800 dark:text-gray-200">With a continuous learning mindset, I embrace challenges and proactively seek opportunities to expand my skill set.</p>
      </div>
      </section>
      <footer className="text-center py-5 text-teal-500">
        &copy; {currentYear} Roberta Freitas
      </footer>

      </main>
    </div>
  );
}
