import React, { useState } from "react";
import Head from "next/head";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import Projects from "../components/Projects";
import Skills from "../components/Skills";
import AboutMe from "../components/AboutMe";
import Footer from "../components/Footer";

function Home() {
  const [currentYear, setCurrentYear] = useState(new Date().getFullYear());
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Roberta Freitas Portfolio</title>
        <meta name="description" content="Generated by Roberta Freitas" />
        <link rel="icon" href="/favicon-portfolio.ico" />
      </Head>
      <main className=" bg-white px-10 md:px-20 lg:px4 dark:bg-gray-900">
        <Navbar darkMode={darkMode} setDarkMode={setDarkMode} />
        <Hero />
        <Projects />
        <Skills />
        <AboutMe />
        <Footer currentYear={currentYear} />
      </main>
    </div>
  );
}

export default Home;
